spring:
  application:
    name: loanManager
  datasource:
    url: jdbc:postgresql://localhost:5432/loanManager
    username: postgres
    password: e5EST4iQ|$8I
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
server:
  port: 8087
  servlet:
    context-path: /api
