spring:
  application:
    name: loanManager
  datasource:
    url: jdbc:postgresql://localhost:5432/loanManager
    username: postgres
    password: Bestdoc@123
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
server:
  port: 8087
  servlet:
    context-path: /api